sudo: required
services:
  - docker
#Update to the latest version
addons:
  apt:
    packages:
      - docker-ce
      
cache:
  directories:
    - $CACHE_DIR
    
env:
  global:
    - CACHE_DIR=$HOME/.cache/docker
    - CACHE_FILE_BASE=$CACHE_DIR/myonosbase.tar.gz
      
      
before_install:
  - DOCKERHUB_USER=chrisioa
  - CI_REGISTRY=docker.io
  - CI_REGISTRY_IMAGE=docker.io/chrisia/myonos
  - docker login -u $DOCKERHUB_USER -p $CI_REGISTRY_PASSWORD_DOCKERHUB

 
  
#Setup execution stages
jobs:
  include:
    - stage: build_onos
      name: Build ONOS
      script:  
        - echo "Building onos"
        - make onos
        - mkdir -p docker-cache
        - docker save chrisioa/myonosbase | gzip > ${CACHE_FILE_BASE}
        
    - stage: build
      name: Build amd64
      script:
        - gunzip -c ${CACHE_FILE_BASE} | docker load
        - make ARCHITECTURES=amd64
        - make ARCHITECTURES=amd64 test
        - make ARCHITECTURES=amd64 push
    - script:
      - gunzip -c ${CACHE_FILE_BASE} | docker load
      - make ARCHITECTURES=arm32v7
      - make ARCHITECTURES=arm32v7 push 
      name: Build arm32v7
    
    - stage: manifest
      name: Docker manifest
      script: 
        - make manifest
      
after_success:
  - docker logout
