version: 2
defaults: &defaults
  working_directory: ~/ktrpojektss18
  machine: true

jobs:
  build_onos:
   <<: *defaults
    steps:
      - checkout
      - run:
          name: Build base onos image
          command: make onos
      - run:
          name: Push base onos image
          command: docker push chrisioa/myonosbase

  build_amd64:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build image for amd64
          command: make ARCHITECTURES=amd64
      - run:
          name: Test image for amd64
          command: make ARCHITECTURES=amd64 test
      - deploy:
          name: Push image for amd64 to dockerhub
          command: make ARCHITECTURES=amd64 push
          
  build_arm32v7:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build image for arm32v7
          command: make ARCHITECTURES=arm32v7
      - deploy:
          name: Push image for arm32v7 to dockerhub
          command: make ARCHITECTURES=arm32v7 push
  
  manifest:
    <<: *defaults
    steps:
      - checkout
      - deploy:
          name: Generate multiarch manifest and push to dockerhub
          command: make manifest

tag_filter: &tag_filter
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_amd64:
          <<: *tag_filter
      - build_arm32v7:
          <<: *tag_filter
      - manifest:
          requires:
            - build_amd64
            - build_arm32v7
          <<: *tag_filter
   
 
