version: 2
defaults: &defaults
  working_directory: ~/myonos
  machine: true

save_docker_cache: &save_docker_cache
  save_cache:
    key: compiled-{{ .Revision }}
    paths: docker-cache

restore_docker_cache: &restore_docker_cache
  restore_cache:
    key: compiled-{{ .Revision }}

load_image_from_cache: &load_image_from_cache
  run:
    name: Load docker image from cache
command: docker load < docker-cache/myonosbase.tar

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build base onos image
          command: make onos && mkdir -p docker-cache
      - run:
          name: Save Cache
          command: |
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
            docker save -o docker-cache/myonosbase.tar chrisioa/myonosbase
      - *save_docker_cache

  build_amd64:
    <<: *defaults
    steps:
      - checkout
      - *restore_docker_cache
      - *load_image_from_cache
      - run:
          name: Build image for amd64
          command: make ARCHITECTURES=amd64
      - run:
          name: Test image for amd64
          command: make ARCHITECTURES=amd64 test
      - deploy:
          name: Push image for amd64 to dockerhub
          command: docker login -u "$DOCKERHUB_USER" -p $DOCKERHUB_PASS && make ARCHITECTURES=amd64 push
  
  build_arm32v7:
    <<: *defaults
    steps:
      - checkout
      - *restore_docker_cache
      - *load_image_from_cache
      - run:
          name: Build image for arm32v7
          command: make ARCHITECTURES=arm32v7
      - deploy:
          name: Push image for arm32v7 to dockerhub
          command: docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS" && make ARCHITECTURES=arm32v7 push

  manifest:
    <<: *defaults
    steps:
      - checkout
      - deploy:
          name: Generate multiarch manifest and push to dockerhub
          command: docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS" && make manifest

requires_build: &requires_build
  requires:
    - build
          
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - build_amd64:
          <<: *requires_build
      - build_arm32v7:
          <<: *requires_build
      - manifest:
          requires:
            - build
            - build_amd64
            - build_arm32v7
