version: '3'
networks:
  controller:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.16.0/24

services:
  onos:
    image: chrisioa/myonos:0.0.1 
    ports:
      # 6653 - OpenFlow
      - "6653:6653"
      # 8181 - GUI
      - "8181:8181"
      # 8101 - ONOS CLI
      - "8101:8101"
      # 9876 - ONOS CLUSTER COMMUNICATION
      - "9876:9876"
      # 5005 - Debugger in IntelliJ
      - "5005:5005"
    environment:
      ONOS_APPS: openflow,pathpainter,project.ioannidis.onosApp #Add fwd for standard forwarding
      KARAF_DEBUG: 'true'
    networks:
      controller:
        ipv4_address: 192.168.16.99
    volumes:
      - ./rundata/onos/data:/data
    
  mininet:
    image: unibaktr/mininet
    privileged: true
    stdin_open: true
    tty: true
    #command: /data/mininetSlice.py
    command: --mac --switch=ovsk,protocols=OpenFlow13 --controller=remote,ip=192.168.16.99,port=6653 --custom /data/topology.py --topo mytopo
    networks:
      controller:
        ipv4_address: 192.168.16.100
    volumes:
      - ./rundata/mininet/data:/data
