COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:KRYO',
    '//core/store/serializers:onos-core-serializers',
    '//core/store/primitives:onos-core-primitives',
    '//core/api:onos-api',
    '//lib:org.apache.karaf.shell.console',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'Interactive intent communication',
    category = 'Traffic Engineering',
    url = 'hub.ktr.uni-bamberg.de',
    description = 'Controller listens for dns messages with "allowTraffic", which enables traffic between specified hosts.',
) 
