#!/bin/bash

#Fresh install
for i in 1 2 3 4 5; do /root/onos/bin/onos-app localhost install /root/onos/project.ioannidis.onosApp/target/project.ioannidis.onosApp-0.0.1.oar && break || sleep 5; done &
#If already installed
for i in 1 2 3 4 5; do /root/onos/bin/onos-app localhost reinstall org.onosproject.project.ioannidis.onosApp /root/onos/project.ioannidis.onosApp/target/project.ioannidis.onosApp-0.0.1.oar && break || sleep 5; done &

for i in 1 2 3 4 5 6 7 8 9 10; do /root/onos/bin/onos-app localhost activate org.onosproject.project.ioannidis.onosApp && break || sleep 6; done &

#Start onos
/root/onos/bin/onos-service server
